name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: ⬇ Git checkout
        uses: actions/checkout@v3

      - name: 💾 Install modules
        run: npm ci

      - name: 🧪 Testing
        run: npm test

      - name: Coverage
        run: npm run test:coverage
        env:
          MONGODB_CONNECTION: ${{ secrets.MONGODB_CONNECTION }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DEBUG: ${{ secrets.DEBUG }}
          ALLOWED_ORIGIN_DEV: ${{ secrets.ALLOWED_ORIGIN_DEV}}
          ALLOWED_ORIGIN_PROD: ${{ secrets.ALLOWED_ORIGIN_PROD}}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
